### ISSUE TITLE
Development of LearnOSM - ongoing work

### ISSUE THREAD

**Issue by Nick-Tallguy** [Nick-Tallguy/Nick-Tallguy.github.io#17]
Hi & thanks for your interest,  

You are reading this issue on a 'staging site' - this is a site I have set up so that development for LearnOSM can be developed and tested before being implemented on the actual site at https://github.com/hotosm/learnosm  

[This is the staging site](http://nick-tallguy.github.io/es/) - open it in a different tab on your browser & compare it with the main site from the link below.  

It's very probable that something you see here will actually arrive in [LearnOSM](http://learnosm.org/en/), but this is still a staging site, so if we try something out, & then decide it was a bad idea, we can either alter it or just roll back a few commits and no changes will have taken place on the main site.

There is nothing to stop us trying out several different things at the same time, or shortly after each other, so if there is something you want to try out, fork this site, make the changes & submit a pull request - if this makes no sense to you, please open an issue on this or the main site explaining exactly what is needed & I'll see what I can do.

**Comment by Nick-Tallguy** [comment]
**8th June 2015**

[Site audit spreadsheet - click on the 'Tidying status' tab](https://docs.google.com/spreadsheets/d/1NlJHTYAYpyyF5o9D8UMAsSzFG7lHY2cIi2mzncx530w/edit#gid=1753852254)  
[Piwik site visit analysis for May 2015](http://piwik.hotosm.org/index.php?module=CoreHome&action=index&idSite=3&period=month&date=2015-05-01#/module=Actions&action=menuGetPageUrls&idSite=3&period=month&date=2015-05-01)  

Discussions on the HOT mailing list, and with me at training sessions (I train people at London UK missing maps events) have confirmed for me that we need to simplify & streamline things for the brand new mappers. A precise of the comments would go something like 'Just tell us what is needed to get helping, nothing else. When we've got the hang of that we can look other things up & perhaps start doing more, but just keep it as simple as possible at the start'.  

As I write this, [LearnOSM](http://learnosm.org/en/beginner/) looks like this, and you would never realise there are sections on mobile surveying, detailed editing, remote mapping, OSM data etc. The beginner section has got so full that nothing else is visible. It's also extremely confusing for any beginner - have they really got to read everything in the beginner section before they can start. I don't think they initially need to read about GPS's or Field Papers, so I would like to see mention of them in the beginner text, but move them into the more appropriate [mobile mapping section of staging site](http://nick-tallguy.github.io/en/mobile-mapping/). If we reduce the number of items in the beginner section, the other menus start to become visible - we have a [Further reading on staging](http://nick-tallguy.github.io/en/beginner/moving-forward/) which could / should provide some more info about other sections of LearnOSM as well as exterior guides (**ToDo**)

My plan at the moment is to continue moving the surveying with a GPS section to Mobile mapping, making sure as much as possible that links are sorted out. This also involves updating image locations and removing some of the many redundant images. - This has involved several hours of work so far, and will take me at least 8 more hours of work at the current rate of progress. Once I have the GPS section sorted to our satisfaction I will make the change on the main site.

When the GPS section has been moved I will start work on the Field Papers section - incidentally @michael63-osm has been extremely busy and we have a fully updated section on the latest version of Field Papers in both German & English - many thanks Michael for a brilliant set of contributions.

**Future moves of sections? - requires discussion**
iD seems to be the editor of choice for complete novices. If we make our beginner section comply with this, then:  
+ move 'id-editor' move from editing to beginner  
+ possibly rename 'detailed editing' to 'editing with JOSM'
+ move anything with josm in the title out of beginner into new JOSM section  
+ expand beginner - moving forward, so that it encourages a transition into JOSM  

**Translations**
There is some excellent work taking place on the site - Swahili, German & Norwegian. As well as clicking through the site, you can also see the progress on the [audit spreadsheet](https://docs.google.com/spreadsheets/d/1NlJHTYAYpyyF5o9D8UMAsSzFG7lHY2cIi2mzncx530w/edit#gid=1753852254). @althio & I have been providing the support for the translators, but althio has been extremely busy with other matters recently, so the translators have mainly had contact from me.

Translations needed - 'id-editor'  currently in editing & anything else that will be remaining in the beginner section should be our first port of call for all languages.  

**How to help**

Think about where we will eventually end up, and how to get there. I suspect that we will see staged access to tasks in the tasking manager, and it would be extremely good if we can support that using resources in LearnOSM.  

Review what I've been doing - mainly need reviewing on the staging site - you can check progress on the audit spreadsheet. Especially if you are multi-lingual, as I may not realize that a linking phrase will need amending. For instance, was GPS referred to in the JOSM section which used to preceed GPS in the beginner. Personally I'm now thinking that the linking comments are a bad idea, as we will need the future flexibility of being able to quickly move sections about & that can be difficult if there are linking comments and you can't recognize them in the language involved. If you find something that needs updating, but you don't know how - **click on the create new issue** green button top right of this screen, and type what the wrong text says, and what it should say - make sure I have enough information to know where to find the problem.

If you are able to help with the tidying, that would be great. I have an offline copy of the site on my laptop, I update using a file manager, text editor, and git in a terminal - sounds complicated, but I started as a novice in October 2015 & now find it very fast and fairly easy. The difficult & slow bit is the checking of the images - I currently sort out the English section, copying the images to their new destination in a section folder & updating the footer of the *.md file. I then repeat the process for the file in the other language - there are many occasions when the file points to another copy of an identical image, and I just change the path to the image previously used - but I do have to check for localized variations - for instance [this Spanish section](http://nick-tallguy.github.io/es/mobile-mapping/using-gps/) has mainly localised images which I have to copy across, rename & then update the path in the *.md file.

Translations - Althio has been snowed under recently, but when he gets the chance we can try out [Transifex](https://www.transifex.com/). It would be good if a few people had a look at the systems described, and made suggestions as to how we could most easily make use of this service - I understand we have free use of the system. At the moment we just need to work out how. I believe there are other methods as well - we need a simple 'how to' that relates to our particular problem.

**Comment by Nick-Tallguy** [comment]
**10/06/2015**

[Site audit spreadsheet - click on the **Staging site**' tab](https://docs.google.com/spreadsheets/d/1NlJHTYAYpyyF5o9D8UMAsSzFG7lHY2cIi2mzncx530w/edit#gid=1753852254)  

[Click here to see the staging site in its current state](http://nick-tallguy.github.io/en/)

Hi, I've had a very busy few days working on updating the staging site. The current position English version looks like this in the index (there are other section headings below the **JOSM-Detailed editing** but I had to stop the screenshot somewhere!
![image](https://cloud.githubusercontent.com/assets/6763965/8082894/adf5c956-0f78-11e5-9426-a87187df4c4e.png)

In the other languages, there are less headings - the Glossary for instance is currently only in English (I'd like to see the Glossary increased & translated - it's on @Anwaario 's ToDo list.).

I think the beginner section in each language is now as complete as I can make it, and I'm now working on moving more files into the JOSM section and sorting that out,

**I need some help please**, especially if you have some language skills. Could you please open the [Site audit spreadsheet - click on the **Staging site**' tab](https://docs.google.com/spreadsheets/d/1NlJHTYAYpyyF5o9D8UMAsSzFG7lHY2cIi2mzncx530w/edit#gid=1753852254)  & look at the beginner section. I need someone to check through the Beginners section - someone for each language column please (preferable if you can speak that language a little, but not essential). There is a row marked up at the top of the Beginners section on the spreadsheet in which to put your name. - [go to the staging site](http://nick-tallguy.github.io/en/) click on the language at the head of the page that refers to the column you've put your name down for, and just review everything in the beginners section - things to check:  
1.  There are no 'double entries' in the index to the left.  
2.  The headings on the spreadsheet appear in the beginners index  
3.   Have a read through the section in your selected language - are there references or links that don't work (I think I've cleared them, but there were a lot & I could easily have missed some)  
4.  Do all the images display okay - we've inherited some broken links, and I think I've cleared most, if not all, but another pair of eyes would be brilliant.  
5.  When you've finished, if everything was okay, just make the square with your name in it go green, or send a message to me or the group so I can update the spreadsheet.  

Once all the beginners section is checked, we need to decide;  
1.  Do we (I) push the staging site across to the main site so that it appears 'as is', or do we wait until  
2.  all files in josm section are also done, or  
3.  Some later stage

Bear in mind there are still translations taking place, so the longer apart the push from one site to another, the more likelihood of 'conflicts' (yes, we get them here as well - the mapping ones were easier for me to deal with!). Not sure how we should reach that decision, but I think it should be the decision of the **Training Working Group**.

In the meantime I'll be working on other bits - we have someone who would like to translate the site into Simplified Chinese (ZH), for instance, and I'd like to get all the 'editing' section moved into JOSM or under other headings as appropriate.

**Comment by Anwaario** [comment]
Hey Nick,

I didn't get this because it was sent to my university email ; weird.

I'm working through my list and might actually start editing by the end of this week.

Best,

Anwar

Anwar K. Abdul-Azim, 2/C
Chief Purser, MPM
California Maritime Academy, CSU
E: Aabdul-Azim@csum.edu<mailto:Aabdul-Azim@csum.edu>
P: 415.562.6927

On Jun 10, 2015, at 6:23 AM, Nick Allen (OSM = Tallguy) <notifications@github.com<mailto:notifications@github.com>> wrote:


10/06/2015

Site audit spreadsheet - click on the Staging site' tab<https://docs.google.com/spreadsheets/d/1NlJHTYAYpyyF5o9D8UMAsSzFG7lHY2cIi2mzncx530w/edit#gid=1753852254>

Click here to see the staging site in its current state<http://nick-tallguy.github.io/en/>

Hi, I've had a very busy few days working on updating the staging site. The current position English version looks like this in the index (there are other section headings below the JOSM-Detailed editing but I had to stop the screenshot somewhere!
[image]<https://cloud.githubusercontent.com/assets/6763965/8082894/adf5c956-0f78-11e5-9426-a87187df4c4e.png>

In the other languages, there are less headings - the Glossary for instance is currently only in English (I'd like to see the Glossary increased & translated - it's on @Anwaario<https://github.com/Anwaario> 's ToDo list.).

I think the beginner section in each language is now as complete as I can make it, and I'm now working on moving more files into the JOSM section and sorting that out,

I need some help please, especially if you have some language skills. Could you please open the Site audit spreadsheet - click on the Staging site' tab<https://docs.google.com/spreadsheets/d/1NlJHTYAYpyyF5o9D8UMAsSzFG7lHY2cIi2mzncx530w/edit#gid=1753852254> & look at the beginner section. I need someone to check through the Beginners section - someone for each language column please (preferable if you can speak that language a little, but not essential). There is a row marked up at the top of the Beginners section on the spreadsheet in which to put your name. - go to the staging site<http://nick-tallguy.github.io/en/> click on the language at the head of the page that refers to the column you've put your name down for, and just review everything in the beginners section - things to check:

1. There are no 'double entries' in the index to the left.

2. The headings on the spreadsheet appear in the beginners index

3. Have a read through the section in your selected language - are there references or links that don't work (I think I've cleared them, but there were a lot & I could easily have missed some)

4. Do all the images display okay - we've inherited some broken links, and I think I've cleared most, if not all, but another pair of eyes would be brilliant.

5. When you've finished, if everything was okay, just make the square with your name in it go green, or send a message to me or the group so I can update the spreadsheet.

Once all the beginners section is checked, we need to decide;

1. Do we (I) push the staging site across to the main site so that it appears 'as is', or do we wait until

2. all files in josm section are also done, or

3. Some later stage

Bear in mind there are still translations taking place, so the longer apart the push from one site to another, the more likelihood of 'conflicts' (yes, we get them here as well - the mapping ones were easier for me to deal with!). Not sure how we should reach that decision, but I think it should be the decision of the Training Working Group.

In the meantime I'll be working on other bits - we have someone who would like to translate the site into Simplified Chinese (ZH), for instance, and I'd like to get all the 'editing' section moved into JOSM or under other headings as appropriate.

�

**Comment by Nick-Tallguy** [comment]
Closing. Info to be held elsewhere
