### ISSUE TITLE
Translation workflow with prose.io

### ISSUE THREAD

**Issue by althio** [Nick-Tallguy/Nick-Tallguy.github.io#25]
@Nick-Tallguy 
For translators using prose.io it might be easier to provide all files at once.
If we provide files as they proceed, it creates apparently diverging forks and eventually their repo goes out of sync when we merge their finished parts.

Or we need admin rights on their github repos so that we keep them in sync and it should reflect on prose.io repos.

cc @yohanboniface (thanks for the diagnosis and input!)

**Comment by Nick-Tallguy** [comment]
Althio,

Thanks for that, I hadn't realized what the problem was. I've been 
sending messages with images to anders, hoping he will update his 
repository following my instructions.

Because of the changes proposed on the staging site, which seems to have 
approval, I suggest that the translators work on the staging site. 
Hopefully I won't be making any more changes to the beginner section. 
Also the start of the JOSM section should be stable.

I have on one occasion 'pulled' from Anders fork without him pushing, 
and then made the changes to get it working on the staging site.

Regards

Nick

On 10/06/15 21:57, althio wrote:
>
> @Nick-Tallguy <https://github.com/Nick-Tallguy>
> For translators using prose.io it might be easier to provide all files 
> at once.
> If we provide files as they proceed, it creates apparently diverging 
> forks and eventually their repo goes out of sync when we merge their 
> finished parts.
>
> Or we need admin rights on their github repos so that we keep them in 
> sync and it should reflect on prose.io repos.
>
> cc @yohanboniface <https://github.com/yohanboniface> (thanks for the 
> diagnosis and input!)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Nick-Tallguy/Nick-Tallguy.github.io/issues/25>.
>


-- 

Nick

Volunteer 'Tallguy' for 
https://wiki.openstreetmap.org/wiki/Humanitarian_OSM_Team

http://www.openstreetmap.org/user/Tallguy

**Comment by Nick-Tallguy** [comment]
Currently trying out  [Transifex](https://www.transifex.com/) as a method of providing translations for the site. It should be a lot simpler for the translators. LearnOSM is listed under the HOT section.

Provided it works okay it may solve all the issues we have been having with keeping forks up to date.

**Comment by Nick-Tallguy** [comment]
Transifex is working well
