### ISSUE TITLE
wiki cleanup

### ISSUE THREAD

**Issue by michael63-osm** [Nick-Tallguy/Nick-Tallguy.github.io#33]
The "English Learning Guides" in the wiki are the resource users are referred to when they click on the blue button on the front page. Much of this material has already been included in learnOSM, we need to remove that from the wiki and decide what to do with the remainder. All documents referenced are Google documents.

The following table summarizes the current state based on a comparison I made today. For our convenience I've numbered the lines so that we can reference entries.

No entry in the learnOSM column means that there is no (rather: I did not find a) corresponding learnOSM document. A checkmark in the remarks column means that learnOSM contains at least as much information as the wiki (and is not a draft document but appears on the website).

| no. | wiki page | learnOSM page | remarks |
| --- | --- | --- | --- |
| 1 | Introduction to OSM | beginner/introduction | :heavy_check_mark: |
| 2 | Starting OSM | beginner/start-osm | :heavy_check_mark: |
| 3 | Editing with Potlatch |  | to be considered obsolete |
| 4 | Getting Started with JOSM | josm/start-josm | :heavy_check_mark: |
| 5 | JOSM Plug ins | josm/josm-plugins | wiki has more contents |
| 6 | Using the GPS | mobile-mapping/using-gps | :heavy_check_mark: |
| 7 | GPS: extrex20 |  |  |
| 8 | Walking Papers |  | obsoleted by Field Papers |
| 9 | Editing with JOSM | josm/more-about-josm <br> josm/editing-with-josm | :heavy_check_mark: |
| 10 | Imagery Offset | josm/aerial-imagery <br> josm/correcting-imagery-offset | :heavy_check_mark: |
| 11 | Moving Forward | beginner/moving-forward | :heavy_check_mark: |
|  |  |  |  |
| 12 | Editing in Detail | josm/josm-tools <br> josm/more-tools <br> josm/josm-relations <br> josm/editing-techniques | :heavy_check_mark: |
| 13 | Conflict Resolution | josm/conflict-resolution | wiki has more details on the resolution form |
| 14 | Using Orbview Imagery in JOSM |  |  |
| 15 | Quality Assurance | draft coordination/quality-assurance |  |
| 16 | Tasking Manager | coordination/tasking-manager | :heavy_check_mark: |
| 17 | Editing the Wiki | draft coordination/editing-the-wiki |  |
| 18 | Creating Custom Presets | josm/creating-presets | :heavy_check_mark: |
| 19 | Private Data Store |  | this is not equivalent to learnOSM draft sys-admin/sds |
|  |  |  |  |
| 20 | PostGIS Configuration | osm-data/setting-up-postgresql | :heavy_check_mark: |
| 21 | Cartography with TileMill | map-design/tilemill | :heavy_check_mark: |
| 22 | Putting Maps on a Website | map-design/mapbox | :heavy_check_mark: |
| 23 | Github Sharing | draft map-design/github |  |
| 24 | WMS Service Configuration | draft map-design/wms |  |
| 25 | Private Data Storage Configuration | draft sys-admin/sds |  |
| 26 | Projections and File Types | osm-data/fileformats | wiki has more details <br> projections are missing in learnOSM |
| 27 | SQLite Databases |  |  |
| 28 | Virtual Machine Setup |  |  |
|  |  |  |  |
| 29 | Mapping Partay |  |  |
| 30 | OSM Resources |  |  |
|  |  |  |  |
| 3x | 7 documents on QGIS |  |  |

My proposal for a first action is to remove the duplicate/obsolete entries from the wiki and summarize the remainder without any subdivision beginner/intermediate/advanced.

**Comment by Nick-Tallguy** [comment]
Michael,

Your right in everything you say, but...

I've had to set some detailed targets for Anwar - this is the link for 
the document 
https://docs.google.com/document/d/1Ms5ypZwowgWvORr9baaV_VwigCrlN5PDp7X7s1SmG9E/edit 
& just in case that doesn't work, the relevant text is

*

 1.

    Create LearnOSM GitHub Wiki Section on Images within LearnOSM

Instructions: create & update your own wiki entry at 
https://github.com/Anwaario/Nick-Tallguy.github.io/wikiwhich full 
explains the desired image sizes, and storage folder that should be 
used. Include how the images are referenced from within guides. Include 
details of any localization of the image name that is needed if the 
image contains text in a specific language.

Links: 
https://github.com/hotosm/learnosm/wiki/Images-guidelines-beta(exisiting 
github wiki entry which will be the eventual target for updates.

https://github.com/Nick-Tallguy/Testing_learnosm/issues/9(more up to 
date guide to images within LearnOSM which may prove helpful)

End Product: Wiki entry at 
https://github.com/Anwaario/Nick-Tallguy.github.io/wikiwhich a mentor 
can copy as a replacement for an out of date wiki entry on the learnosm 
wiki.

Deadline:



2.   Review iD Editor GitHub Wiki Section

Instructions: Read the two sections, making a note of any differences 
that may be found.

Links: 
https://github.com/Nick-Tallguy/Nick-Tallguy.github.io/issues/32issue 
created with instructions duplicated here. 
http://learnosm.org/en/beginner/id-editor/LearnOSM article, and 
https://github.com/hotosm/learnosm/wiki/iD-Editorwiki entry.

End Product: Update / comment added to 
https://github.com/Nick-Tallguy/Nick-Tallguy.github.io/issues/32showing 
which if any additions need to be made to the LearnOSM entry.

Deadline:



3. Review Rest of GitHub Wiki Sections

Instructions: Check the content of only the beginner section of the 
guides at 
https://github.com/hotosm/learnosm/wiki/English-Learning-Guides, compare 
them with the guides on LearnOSM (they may be in different sections), 
and create a new issue on 
https://github.com/Nick-Tallguy/Nick-Tallguy.github.io/issuesfor each 
wiki heading with notes explaining what differences need adding to LearnOSM

Links: https://github.com/hotosm/learnosm/wiki/English-Learning-Guides

https://github.com/Nick-Tallguy/Nick-Tallguy.github.io/issues

http://learnosm.org/en/


End Product: An issue per entry within the beginner section of the 
github wiki, the issue listing any amendments that may be needed to LearnOSM

Deadline:


*
Can you hang fire on the beginner section, leaving to him. I'm hoping he 
starts to accelerate because otherwise it's mainly down to you & me.

I've just created a 'false guide' as a temporary thing - something to 
test out.  To view http://nick-tallguy.github.io/zh/josm/start-josm/

The idea is to create one of these for every guide which is 'missing', 
with links to the guides that are present.  We can use these as a 
temporary thing before full translation, and to cover links to the 
google docs.

Got to rush now - but your views appreciated.

Nick

On 07/07/15 15:00, Michael Heißmeier wrote:
>
> The "English Learning Guides" in the wiki are the resource users are 
> referred to when they click on the blue button on the front page. Much 
> of this material has already been included in learnOSM, we need to 
> remove that from the wiki and decide what to do with the remainder. 
> All documents referenced are Google documents.
>
> The following table summarizes the current state based on a comparison 
> I made today. For our convenience I've numbered the lines so that we 
> can reference entries.
>
> No entry in the learnOSM column means that there is no (rather: I did 
> not find a) corresponding learnOSM document. A checkmark in the 
> remarks column means that learnOSM contains at least as much 
> information as the wiki (and is not a draft document but appears on 
> the website).
>
> no. 	wiki page 	learnOSM page 	remarks
> 1 	Introduction to OSM 	beginner/introduction 	:heavy_check_mark:
> 2 	Starting OSM 	beginner/start-osm 	:heavy_check_mark:
> 3 	Editing with Potlatch 	
> 	to be considered obsolete
> 4 	Getting Started with JOSM 	josm/start-josm 	:heavy_check_mark:
> 5 	JOSM Plug ins 	josm/josm-plugins 	wiki has more contents
> 6 	Using the GPS 	mobile-mapping/using-gps 	:heavy_check_mark:
> 7 	GPS: extrex20 	
> 	
> 8 	Walking Papers 	
> 	obsoleted by Field Papers
> 9 	Editing with JOSM 	josm/more-about-josm
> josm/editing-with-josm 	:heavy_check_mark:
> 10 	Imagery Offset 	josm/aerial-imagery
> josm/correcting-imagery-offset 	:heavy_check_mark:
> 11 	Moving Forward 	beginner/moving-forward 	:heavy_check_mark:
>
> 	
> 	
> 	
> 12 	Editing in Detail 	josm/josm-tools
> josm/more-tools
> josm/josm-relations
> josm/editing-techniques 	:heavy_check_mark:
> 13 	Conflict Resolution 	josm/conflict-resolution 	wiki has more 
> details on the resolution form
> 14 	Using Orbview Imagery in JOSM 	
> 	
> 15 	Quality Assurance 	draft coordination/quality-assurance 	
> 16 	Tasking Manager 	coordination/tasking-manager 	:heavy_check_mark:
> 17 	Editing the Wiki 	draft coordination/editing-the-wiki 	
> 18 	Creating Custom Presets 	josm/creating-presets 	:heavy_check_mark:
> 19 	Private Data Store 	
> 	this is not equivalent to learnOSM draft sys-admin/sds
>
> 	
> 	
> 	
> 20 	PostGIS Configuration 	osm-data/setting-up-postgresql 
> :heavy_check_mark:
> 21 	Cartography with TileMill 	map-design/tilemill 	:heavy_check_mark:
> 22 	Putting Maps on a Website 	map-design/mapbox 	:heavy_check_mark:
> 23 	Github Sharing 	draft map-design/github 	
> 24 	WMS Service Configuration 	draft map-design/wms 	
> 25 	Private Data Storage Configuration 	draft sys-admin/sds 	
> 26 	Projections and File Types 	osm-data/fileformats 	wiki has more 
> details
> projections are missing in learnOSM
> 27 	SQLite Databases 	
> 	
> 28 	Virtual Machine Setup 	
> 	
>
> 	
> 	
> 	
> 29 	Mapping Partay 	
> 	
> 30 	OSM Resources 	
> 	
>
> 	
> 	
> 	
> 3x 	7 documents on QGIS 	
> 	
>
> My proposal for a first action is to remove the duplicate/obsolete 
> entries from the wiki and summarize the remainder without any 
> subdivision beginner/intermediate/advanced.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Nick-Tallguy/Nick-Tallguy.github.io/issues/33>.
>


-- 

Nick

Volunteer 'Tallguy' for 
https://wiki.openstreetmap.org/wiki/Humanitarian_OSM_Team

http://www.openstreetmap.org/user/Tallguy

**Comment by Nick-Tallguy** [comment]
@michael63-osm I've updated the wiki in line with your comments above. I will create a detailed guide of how to create an interim document for adding to the site with a view to getting our intern to create more - these two links are examples I have created;  
http://nick-tallguy.github.io/en/intermediate/editing-the-wiki/  
&  
http://nick-tallguy.github.io/de/intermediate/editing-the-wiki/

Regards

Nick

**Comment by Nick-Tallguy** [comment]
Closing here. Please see https://github.com/hotosm/learnosm/issues/527
